---
- name: check mirror-registry container
  shell: podman ps -a | grep mirror-registry
  register: mirror_registry
  ignore_errors: true

- name: install podman and httpd-tools
  when: mirror_registry.rc != 0
  yum:
    name: "{{ item }}"
    state: present
  loop:
  - podman
  - httpd-tools

- name: generate registry certificate
  when: mirror_registry.rc != 0
  shell:  openssl req -newkey rsa:4096 -nodes -sha256 -keyout /opt/registry/certs/domain.key -x509 -days 3650 -out /opt/registry/certs/domain.crt -subj "/C=CN/ST=zhejiang/L=hangzhou/O=Red Hat/OU=GPS/CN={{ ocp.registry.name }}.{{ ocp.base_domain }}"
- name: generate user and password
  when: mirror_registry.rc != 0
  shell: htpasswd -bBc /opt/registry/auth/htpasswd {{ ocp.registry.username }} {{ ocp.registry.password }}
- name: ca trust
  when: mirror_registry.rc != 0
  shell:
    cmd: |
      \cp /opt/registry/certs/domain.crt /etc/pki/ca-trust/source/anchors/domain.crt 
       update-ca-trust
